dist: trusty
language:
  - cpp

compiler:
  - gcc

# matrix:
#     fast_finish: true
#     include:
#         - os: linux
#           compiler: gcc
#           env: TARGET=desktop
#           addons:
#               apt:
#                   sources:
#                       - ubuntu-toolchain-r-test
#                       - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
#                   packages:
#                       - g++-5
#                       - qt510-meta-minimal
#                       - qt510script

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - gcc-6
      - g++-6
      - cmake
      - qt510-meta-minimal
      - qt510script

script:
  # Link gcc-6 and g++-6 to their standard commands
  # - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  # - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake .
  - make
  - ./dadm